# Generated by Django 2.2 on 2021-04-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210419_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetail',
            new_name='Furniture',
        ),
    ]
