# Generated by Django 2.2 on 2021-04-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210419_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='api.Product'),
        ),
    ]
