# Generated by Django 2.2 on 2021-04-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210427_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='furniture',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Product'),
        ),
    ]
