# Generated by Django 2.2 on 2021-04-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
